# Generated by Django 3.0.3 on 2020-10-26 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201025_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_completed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
